services:
  minio:
    image: minio/minio:RELEASE.2023-04-13T03-08-07Z
    container_name: minio_pranoto
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: miniopassword
    volumes:
      - ./minio/data:/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
  mc:
    image: minio/mc:RELEASE.2023-04-12T02-21-51Z
    container_name: mc_pranoto
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "/usr/bin/mc config host rm local
                  /usr/bin/mc config host add local http://minio:9000 minioadmin miniopassword
                  /usr/bin/mc admin info 
                  /usr/bin/mc mb local/pranoto-bucket
                  echo "TODO: Change policy on production"
                  /usr/bin/mc anonymous set download local/pranoto-bucket
                  /usr/bin/mc admin user add local pranoto_access_key pranoto_secret_key
                  /usr/bin/mc admin policy attach local readwrite --user pranoto_access_key"
  nats:
    image: nats:2-alpine
    container_name: nats_pranoto
    command: "--http_port 8222"
    ports:
      - 4222:4222
      - 8222:8222
    restart: unless-stopped
  postgres:
    image: postgres:15-alpine
    container_name: pranoto-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pranoto_password
      POSTGRES_USER: pranoto_user
      POSTGRES_DB: pranoto_db
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
