name: Build CI

on:
  workflow_dispatch: null
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        include:
          - node-version: 18.x
            targets: node18
          - node-version: 20.x
            targets: node20
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
      - run: npm ci
      - run: npm run build --if-present
      - run: NODE_OPTIONS='--no-experimental-fetch' npm test && npx codecov